[package]
name = "alg"
version = "0.1.0"
authors = ["C. Jeremiah Schneider <schneider@br-tech.de>"]

[dependencies]

[[bin]]
#name = "find_digits"
#name = "sherlock_squares"
#name = "coin_change"
name = "journey_to_moon"
